// <auto-generated />
using BookRESTFulService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookRESTFulService.Data.Migrations.Book
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookRESTFulService.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<string>("Category")
                        .HasMaxLength(50);

                    b.Property<string>("Edition");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PublishYear");

                    b.Property<int>("Quantity");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.HasKey("Isbn");

                    b.ToTable("Books");

                    b.HasData(
                        new { Isbn = "978-1491987650", Category = "Programming", Edition = "1st Edition", Price = 65m, PublishYear = 2017, Quantity = 5, Title = "C# 7.0 in a Nutshell : The Definitive Reference" },
                        new { Isbn = "978-1119449270", Category = "Programming", Edition = "1st Edition", Price = 35m, PublishYear = 2018, Quantity = 8, Title = "Professional C# 7 and .NET Core 2.0" },
                        new { Isbn = "978-1484230176", Category = "Programming", Edition = "1st Edition", Price = 40m, PublishYear = 2017, Quantity = 5, Title = "Pro C# 7: With .NET and .NET Core" },
                        new { Isbn = "978-1509307760", Category = "Programming", Edition = "9th Edition", Price = 31m, PublishYear = 2018, Quantity = 7, Title = "Microsoft Visual C# Step by Step " },
                        new { Isbn = "978-1617291340", Category = "Programming", Edition = "3rd Edition", Price = 75m, PublishYear = 2014, Quantity = 3, Title = "C# in Depth" },
                        new { Isbn = "978-1518877551", Category = "Programming", Edition = "2nd Edition", Price = 59m, PublishYear = 2015, Quantity = 6, Title = "C# For Beginners : The tactical guidebook " },
                        new { Isbn = "978-1973727767", Category = "Programming", Edition = "4th Edition", Price = 55m, PublishYear = 2015, Quantity = 8, Title = "C# for Tweens and Teens" },
                        new { Isbn = "978-1890774943", Category = "Programming", Edition = "6th Edition", Price = 42m, PublishYear = 2016, Quantity = 9, Title = "Murach's C# 2015 " },
                        new { Isbn = "978-1617294532", Category = "Programming", Edition = "4th Edition", Price = 72m, PublishYear = 2018, Quantity = 5, Title = "C# in Depth" },
                        new { Isbn = "978-1119428114", Category = "Programming", Edition = "1st Edition", Price = 60m, PublishYear = 2018, Quantity = 4, Title = "C# 7.0 All-in-One For Dummies" },
                        new { Isbn = "978-1449343507", Category = "Programming", Edition = "3rd Edition", Price = 63m, PublishYear = 2016, Quantity = 0, Title = "Head First C#" },
                        new { Isbn = "978-0735667457", Category = "Programming", Edition = "4th Edition", Price = 39m, PublishYear = 2012, Quantity = 2, Title = "CLR via C# (Developer Reference)" },
                        new { Isbn = "978-1119458685", Category = "Programming", Edition = "1st Edition", Price = 51m, PublishYear = 2018, Quantity = 2, Title = "Beginning C# 7 Programming with Visual Studio 2017" },
                        new { Isbn = "978-1484213339", Category = "Programming", Edition = "7th Edition", Price = 55m, PublishYear = 2015, Quantity = 4, Title = "C# 6.0 and the .NET 4.6 Framework" },
                        new { Isbn = "978-1509303588", Category = "Programming", Edition = "6th Edition", Price = 58m, PublishYear = 2018, Quantity = 0, Title = "Essential C# 7.0" },
                        new { Isbn = "978-1491978917", Category = "Programming", Edition = "5th Edition", Price = 47m, PublishYear = 2018, Quantity = 1, Title = "Learning PHP, MySQL & JavaScript" },
                        new { Isbn = "978-0134301846", Category = "Programming", Edition = "5th Edition", Price = 43m, PublishYear = 2018, Quantity = 7, Title = "PHP and MySQL for Dynamic Web Sites" },
                        new { Isbn = "978-1119149224", Category = "Programming", Edition = "1st Edition", Price = 58m, PublishYear = 2019, Quantity = 5, Title = "PHP & MySQL: Server-side Web Development" },
                        new { Isbn = "978-1943872381", Category = "Programming", Edition = "3rd Edition", Price = 60m, PublishYear = 2017, Quantity = 1, Title = "Murach's PHP and MySQL" },
                        new { Isbn = "978-1491905012", Category = "Programming", Edition = "1st Edition", Price = 65m, PublishYear = 2015, Quantity = 0, Title = "Modern PHP: New Features and Good Practices" },
                        new { Isbn = "978-0134291253", Category = "Programming", Edition = "5th Edition", Price = 35m, PublishYear = 2016, Quantity = 3, Title = "PHP for the Web: Visual QuickStart Guide" },
                        new { Isbn = "978-1491918661", Category = "Programming", Edition = "4th Edition", Price = 42m, PublishYear = 2015, Quantity = 4, Title = "Learning PHP, MySQL & JavaScript" },
                        new { Isbn = "978-1449363758", Category = "Programming", Edition = "3rd Edition", Price = 63m, PublishYear = 2014, Quantity = 5, Title = "PHP Cookbook" },
                        new { Isbn = "978-1119468387", Category = "Programming", Edition = "1st Edition", Price = 55m, PublishYear = 2018, Quantity = 8, Title = "PHP, MySQL, & JavaScript All-in-One" },
                        new { Isbn = "978-0321833891", Category = "Programming", Edition = "5th Edition", Price = 58m, PublishYear = 2017, Quantity = 0, Title = "PHP and MySQL Web Development" },
                        new { Isbn = "978-1484206362", Category = "Programming", Edition = "3rd Edition", Price = 43m, PublishYear = 2015, Quantity = 0, Title = "PHP Solutions : Dynamic Web Design Made Easy " },
                        new { Isbn = "978-0321832184", Category = "Programming", Edition = "3rd Edition", Price = 39m, PublishYear = 2013, Quantity = 4, Title = "PHP Advanced and Object-Oriented Programming" },
                        new { Isbn = "978-1449392772", Category = "Programming", Edition = "3rd Edition", Price = 66m, PublishYear = 2013, Quantity = 7, Title = "Programming PHP: Creating Dynamic Web Pages" },
                        new { Isbn = "978-1430260431", Category = "Programming", Edition = "5th Edition", Price = 72m, PublishYear = 2018, Quantity = 9, Title = "Beginning PHP and MySQL" },
                        new { Isbn = "978-0596006303", Category = "Programming", Edition = "1st Edition", Price = 38m, PublishYear = 2009, Quantity = 6, Title = "Head First PHP & MySQL" },
                        new { Isbn = "978-0470413968", Category = "Programming", Edition = "1st Edition", Price = 44m, PublishYear = 2010, Quantity = 8, Title = "Beginning PHP 5.3" },
                        new { Isbn = "978-0994346988", Category = "Programming", Edition = "6th Edition", Price = 53m, PublishYear = 2017, Quantity = 9, Title = "PHP & MySQL: Novice to Ninja" },
                        new { Isbn = "978-1430260318", Category = "Programming", Edition = "4th Edition", Price = 52m, PublishYear = 2013, Quantity = 5, Title = "PHP Objects, Patterns, and Practice" },
                        new { Isbn = "978-1943872077", Category = "Programming", Edition = "5th Edition", Price = 70m, PublishYear = 2017, Quantity = 4, Title = "Murach's Java Programming" },
                        new { Isbn = "978-0134685991", Category = "Programming", Edition = "3rd Edition", Price = 62m, PublishYear = 2018, Quantity = 0, Title = "Effective Java" },
                        new { Isbn = "978-1260440218", Category = "Programming", Edition = "8th Edition", Price = 45m, PublishYear = 2018, Quantity = 2, Title = "Java: A Beginner's Guide" },
                        new { Isbn = "978-0596009205", Category = "Programming", Edition = "2nd Edition", Price = 48m, PublishYear = 2003, Quantity = 2, Title = "Head First Java" },
                        new { Isbn = "978-0134802213", Category = "Programming", Edition = "7th Edition", Price = 40m, PublishYear = 2015, Quantity = 4, Title = "Starting Out with Java" },
                        new { Isbn = "978-1259589331", Category = "Programming", Edition = "10th Edition", Price = 33m, PublishYear = 2017, Quantity = 0, Title = "Java: The Complete Reference" },
                        new { Isbn = "978-1492037255", Category = "Programming", Edition = "7th Edition", Price = 52m, PublishYear = 2018, Quantity = 1, Title = "Java in a Nutshell" },
                        new { Isbn = "978-0135166307", Category = "Programming", Edition = "11th Edition", Price = 38m, PublishYear = 2018, Quantity = 7, Title = "Core Java Volume I" },
                        new { Isbn = "978-0321349606", Category = "Programming", Edition = "1st Edition", Price = 60m, PublishYear = 2015, Quantity = 5, Title = "Java Concurrency in Practice" },
                        new { Isbn = "978-1119247791", Category = "Programming", Edition = "5th Edition", Price = 66m, PublishYear = 2017, Quantity = 1, Title = "Java All-in-One For Dummies" },
                        new { Isbn = "978-0134777566", Category = "Programming", Edition = "4th Edition", Price = 72m, PublishYear = 2017, Quantity = 0, Title = "Java 9 for Programmers" },
                        new { Isbn = "978-0672324536", Category = "Programming", Edition = "2nd Edition", Price = 38m, PublishYear = 2018, Quantity = 3, Title = "Data Structures and Algorithms in Java" },
                        new { Isbn = "978-1119235538", Category = "Programming", Edition = "5th Edition", Price = 48m, PublishYear = 2017, Quantity = 4, Title = "Beginning Programming with Java For Dummies" },
                        new { Isbn = "978-1491929568", Category = "Programming", Edition = "1st Edition", Price = 55m, PublishYear = 2016, Quantity = 5, Title = "Think Java: How to Think Like a Computer Scientist" },
                        new { Isbn = "978-0134462028", Category = "Programming", Edition = "9th Edition", Price = 53m, PublishYear = 2017, Quantity = 8, Title = "Java Software Solutions" },
                        new { Isbn = "978-1119056447", Category = "Programming", Edition = "6th Edition", Price = 68m, PublishYear = 2016, Quantity = 0, Title = "Big Java, Binder Ready Version: Early Objects" },
                        new { Isbn = "978-1890774783", Category = "Programming", Edition = "3rd Edition", Price = 43m, PublishYear = 2014, Quantity = 0, Title = "Murach's Java Servlets and JSP" },
                        new { Isbn = "978-0134177298", Category = "Programming", Edition = "10th Edition", Price = 38m, PublishYear = 2017, Quantity = 4, Title = "Core Java, Volume II" },
                        new { Isbn = "978-1449358457", Category = "Programming", Edition = "1st Edition", Price = 39m, PublishYear = 2014, Quantity = 2, Title = "Java Performance: The Definitive Guide" },
                        new { Isbn = "978-1484231494", Category = "Programming", Edition = "7th Edition", Price = 52m, PublishYear = 2017, Quantity = 4, Title = "Pro ASP.NET Core MVC 2" },
                        new { Isbn = "978-1890774950", Category = "Programming", Edition = "6th Edition", Price = 56m, PublishYear = 2016, Quantity = 0, Title = "Murach's ASP.NET 4.6 Web Programming with C# 2015" },
                        new { Isbn = "978-1119181316", Category = "Programming", Edition = "1st Edition", Price = 48m, PublishYear = 2018, Quantity = 1, Title = "Front-end Development with ASP.NET Core, Angular, and Bootstrap" },
                        new { Isbn = "978-1509304417", Category = "Programming", Edition = "1st Edition", Price = 35m, PublishYear = 2018, Quantity = 7, Title = "Programming ASP.NET Core" },
                        new { Isbn = "978-1509304066", Category = "Programming", Edition = "1st Edition", Price = 55m, PublishYear = 2017, Quantity = 5, Title = "ASP.NET Core Application Development" },
                        new { Isbn = "978-1118794753", Category = "Programming", Edition = "1st Edition", Price = 72m, PublishYear = 2014, Quantity = 1, Title = "Professional ASP.NET MVC 5" },
                        new { Isbn = "978-1617294617", Category = "Programming", Edition = "1st Edition", Price = 65m, PublishYear = 2018, Quantity = 0, Title = "ASP.NET Core in Action" },
                        new { Isbn = "978-1788293600", Category = "Programming", Edition = "1st Edition", Price = 33m, PublishYear = 2018, Quantity = 3, Title = "ASP.NET Core 2 and Angular 5" },
                        new { Isbn = "978-1119410263", Category = "Programming", Edition = "1st Edition", Price = 49m, PublishYear = 2018, Quantity = 4, Title = "Professional ASP.NET: Core 2.0" },
                        new { Isbn = "978-1430265290", Category = "Programming", Edition = "5th Edition", Price = 52m, PublishYear = 2016, Quantity = 5, Title = "Pro ASP.NET MVC 5" },
                        new { Isbn = "978-1491961735", Category = "Programming", Edition = "1st Edition", Price = 54m, PublishYear = 2017, Quantity = 8, Title = "Building Microservices with ASP.NET Core" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
